name: PR Preview Create

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/pr-preview.yml \
            --stack-name pr-preview-${{ github.event.pull_request.number }} \
            --parameter-overrides \
              PRNumber=${{ github.event.pull_request.number }} \
              KeyName=new \
              AMI=ami-0c398cb65a93047f2 \
              SubnetId=subnet-0a0c27952b7bab8ee \
              SecurityGroupId=sg-0dfdfeed826aa181c \
              DBSnapshotIdentifier=temp \
              DBSubnetGroup=default-vpc-0846b504af3e035bd \
              DBUsername=admin \
              DBPassword=${{ secrets.DB_PASSWORD }} \
              GitHubToken=${{ secrets.GH_CLONE_TOKEN }} \
              RepoURL=https://github.com/sanjayjangir1093/cicd.git \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Comment URL
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          URL=$(aws cloudformation describe-stacks \
            --stack-name pr-preview-${{ github.event.pull_request.number }} \
            --query "Stacks[0].Outputs[?OutputKey=='AppURL'].OutputValue" \
            --output text)

          gh pr comment ${{ github.event.pull_request.number }} \
            --body "ðŸš€ PR Preview ready: $URL"
